#!/bin/csh
# Shell script to run gcl test
#

source ~/.cshrc
cd ~/gambit/sources
make gcl
cd ../test
echo '*************** Finished re-compiling ************'

rm junk
cp gclini.koo.test gclini.gcl
newgcl > junk
cp ~/gambit/bin/gclini.gcl gclini.gcl
mv algtest.out algtest.koo.out
echo '*************** Finished test.gcl ****************'

diff chainst.efg chainst.efg.old
diff holdout.efg holdout.efg.old
diff condjury.efg condjury.efg.old
diff 2x2a.out 2x2a.out.old
diff bhg3.out bhg3.out.old
diff algtest.koo.out algtest.koo.out.old
echo '*************** Finished diffing *****************'


