//
// $Source$
// $Date$
// $Revision$
//
// DESCRIPTION:
// Declaration of constants used for extensive form menu items
//

#ifndef EFGCONST_H
#define EFGCONST_H

typedef enum {
  efgmenuEDIT_INSERT = 1100,
  efgmenuEDIT_DELETE = 1101,

  efgmenuEDIT_INFOSET = 920,
  efgmenuEDIT_INFOSET_MERGE = 1400,
  efgmenuEDIT_INFOSET_BREAK = 1401,
  efgmenuEDIT_INFOSET_JOIN = 1402,
  efgmenuEDIT_INFOSET_PLAYER = 1405,
  efgmenuEDIT_INFOSET_REVEAL = 1407,
  efgmenuEDIT_INFOSET_SPLIT = 1410,

  efgmenuEDIT_OUTCOMES = 1319,
  efgmenuEDIT_OUTCOMES_DELETE = 1325,
  efgmenuEDIT_OUTCOMES_NEW = 1326,

  efgmenuEDIT_GAME = 1419,
  efgmenuEDIT_NODE = 1420,
  efgmenuEDIT_MOVE = 1421,

  efgmenuVIEW_PROFILES = 1850,
  efgmenuVIEW_NAVIGATION = 1860,
  efgmenuVIEW_OUTCOMES = 1861,
  efgmenuVIEW_SUPPORTS = 1862,
  efgmenuVIEW_ZOOMIN = 1601,
  efgmenuVIEW_ZOOMOUT = 1602,

  efgmenuFORMAT_LEGEND = 1604,
  efgmenuFORMAT_SAVE = 1605,
  efgmenuFORMAT_LOAD = 1606,
  efgmenuFORMAT_FONTS = 1612,
  efgmenuFORMAT_FONTS_ABOVENODE = 1613,
  efgmenuFORMAT_FONTS_BELOWNODE = 1614,
  efgmenuFORMAT_FONTS_AFTERNODE = 1615,
  efgmenuFORMAT_FONTS_ABOVEBRANCH = 1616,
  efgmenuFORMAT_FONTS_BELOWBRANCH = 1617,
  efgmenuFORMAT_DISPLAY = 1603,
  efgmenuFORMAT_DISPLAY_DECIMALS = 1618,
  efgmenuFORMAT_DISPLAY_LAYOUT = 1620,

  efgmenuTOOLS_SUBGAME = 1349,
  efgmenuTOOLS_SUBGAME_MARKALL = 1350,
  efgmenuTOOLS_SUBGAME_MARK = 1351,
  efgmenuTOOLS_SUBGAME_UNMARKALL = 1352,
  efgmenuTOOLS_SUBGAME_UNMARK = 1354,

  efgmenuTOOLS_SUPPORT = 1799,
  efgmenuTOOLS_SUPPORT_UNDOMINATED = 1800,
  efgmenuTOOLS_SUPPORT_NEW = 1801,
  efgmenuTOOLS_SUPPORT_EDIT = 1802,
  efgmenuTOOLS_SUPPORT_DELETE = 1803,
  efgmenuTOOLS_SUPPORT_SELECT = 1810,
  efgmenuTOOLS_SUPPORT_SELECT_FROMLIST = 1811,
  efgmenuTOOLS_SUPPORT_SELECT_PREVIOUS = 1812,
  efgmenuTOOLS_SUPPORT_SELECT_NEXT = 1813,
  efgmenuTOOLS_SUPPORT_REACHABLE = 1814,

  efgmenuTOOLS_EQUILIBRIUM = 1539,
  efgmenuTOOLS_EQUILIBRIUM_STANDARD = 1540,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM = 1502,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_EFG = 1503,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_EFG_ENUMPURE = 1506,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_EFG_LCP = 1507,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_EFG_LP = 1508,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_EFG_LIAP = 1509,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_EFG_POLENUM = 1538,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_EFG_QRE = 1510,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG = 1505,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG_ENUMPURE = 1511,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG_ENUMMIXED = 1512,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG_LCP = 1513,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG_LP = 1514,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG_LIAP = 1515,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG_SIMPDIV = 1516,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG_POLENUM = 1539,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG_QRE = 1517,
  efgmenuTOOLS_EQUILIBRIUM_CUSTOM_NFG_QREGRID = 1518,

  efgmenuTOOLS_NFG = 1521,
  efgmenuTOOLS_NFG_REDUCED = 1504,
  efgmenuTOOLS_NFG_AGENT = 1519,
  
  // Menu items for profiles window
  efgmenuPROFILES_FILTER = 2000,
  efgmenuPROFILES_NEW = 2001,
  efgmenuPROFILES_CLONE = 2002,
  efgmenuPROFILES_RENAME = 2003,
  efgmenuPROFILES_EDIT = 2004,
  efgmenuPROFILES_DELETE = 2005

} guiEfgMenuItems;


#endif // EFGCONST_H









