version: 2

sphinx:
  configuration: doc/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libgmp-dev

python:
  install:
    - requirements: doc/requirements.txt
    - method: setuptools
      path: "."
