version: 2

sphinx:
  configuration: doc/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.14"
  apt_packages:
    - libgmp-dev
    - pandoc
    - texlive-full

python:
  install:
    - method: pip
      path: "."
      extra_requirements:
        - doc
