version: 2

sphinx:
  configuration: doc/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.14"
  apt_packages:
    - libgmp-dev
    - pandoc
    - texlive-full
  jobs:
    pre_install:
      - pip install --upgrade --force-reinstall "draw_tree @ git+https://github.com/gambitproject/draw_tree.git@main#egg=draw_tree"

python:
  install:
    - requirements: doc/requirements.txt
    - method: setuptools
      path: "."
