version: 2

sphinx:
  configuration: doc/conf.py

formats: all

build:
  os: ubuntu-22.04
  tools:
    python: "3.14"
  apt_packages:
    - libgmp-dev
    - pandoc
    - texlive-full
  jobs:
    # Create CSV for catalog table in docs
    post_install:
      - $READTHEDOCS_VIRTUALENV_PATH/bin/python build_support/catalog/update.py

python:
  install:
    - requirements: doc/requirements.txt
    - method: pip
      path: "."
