//
// FILE: efgaccl.h -- gives names to various Extensive form GUI options
//
// $Id$
//

#ifndef EFGACCL_H
#define EFGACCL_H

#include "accels.h"
#define 	NUM_EFG_EVENTS	79
AccelEvent efg_events[NUM_EFG_EVENTS]=
{
AccelEvent("Save",FILE_SAVE),
AccelEvent("Print",FILE_OUTPUT),
AccelEvent("Close",FILE_CLOSE),
AccelEvent("NodeAdd",NODE_ADD),
AccelEvent("NodeDelete",NODE_DELETE),
AccelEvent("NodeInsert",NODE_INSERT),
AccelEvent("NodeLabel",NODE_LABEL),
AccelEvent("SetMark",NODE_SET_MARK),
AccelEvent("GoToMark",NODE_GOTO_MARK),
AccelEvent("ActionDelete",ACTION_DELETE),
AccelEvent("ActionInsert",ACTION_INSERT),
AccelEvent("ActionLabel",ACTION_LABEL),
AccelEvent("ActionProbs",ACTION_PROBS),
AccelEvent("InfosetMerge",INFOSET_MERGE),
AccelEvent("InfosetBreak",INFOSET_BREAK),
AccelEvent("InfosetSplit",INFOSET_SPLIT),
AccelEvent("InfosetJoin",INFOSET_JOIN),
AccelEvent("InfosetLabel",INFOSET_LABEL),
AccelEvent("InfosetPlayer",INFOSET_SWITCH_PLAYER),
AccelEvent("InfosetReveal",INFOSET_REVEAL),
AccelEvent("OutcomeAttach",TREE_OUTCOMES_ATTACH),
AccelEvent("OutcomeDetach",TREE_OUTCOMES_DETACH),
AccelEvent("OutcomeLabel",TREE_OUTCOMES_LABEL),
AccelEvent("OutcomePayoffs",TREE_OUTCOMES_PAYOFFS),
AccelEvent("TreeCopy",TREE_COPY),
AccelEvent("TreeMove",TREE_MOVE),
AccelEvent("TreeDelete",TREE_DELETE),
AccelEvent("TreeLabel",TREE_LABEL_LABEL),
AccelEvent("TreePlayers",TREE_PLAYERS),
AccelEvent("TreeInfosetss",TREE_INFOSETS),
AccelEvent("Subgames MarkAll",SUBGAME_SOLVE),
AccelEvent("Subgames Mark",SUBGAME_SET),
AccelEvent("Subgames UnmarkAll",SUBGAME_CLEARALL),
AccelEvent("Subgames Unmark",SUBGAME_CLEARONE),
AccelEvent("Subgames CollapseAll",SUBGAME_COLLAPSEALL),
AccelEvent("Subgames Collapse",SUBGAME_COLLAPSEONE),
AccelEvent("Subgames ExpandLevel",SUBGAME_EXPANDONE),
AccelEvent("Subgames ExpandBranch",SUBGAME_EXPANDBRANCH),
AccelEvent("Subgames ExpandAll",SUBGAME_EXPANDALL),
AccelEvent("SupportsElimDom",SUPPORTS_ELIMDOM),
AccelEvent("SupportsSelect",SUPPORTS_SUPPORTS),
AccelEvent("SolveStandard",SOLVE_STANDARD),
AccelEvent("EF EnumPure",SOLVE_CUSTOM_EFG_ENUMPURE),
AccelEvent("EF LCP",SOLVE_CUSTOM_EFG_LCP),
AccelEvent("EF LP",SOLVE_CUSTOM_EFG_LP),
AccelEvent("EF Liap",SOLVE_CUSTOM_EFG_LIAP),
AccelEvent("EF PolEnum",SOLVE_CUSTOM_EFG_POLENUM),
AccelEvent("EF QRE",SOLVE_CUSTOM_EFG_QRE),
AccelEvent("NF EnumPure",SOLVE_CUSTOM_NFG_ENUMPURE),
AccelEvent("NF EnumMixed",SOLVE_CUSTOM_NFG_ENUMMIXED),
AccelEvent("NF LCP",SOLVE_CUSTOM_NFG_LCP),
AccelEvent("NF LP",SOLVE_CUSTOM_NFG_LP),
AccelEvent("NF Liap",SOLVE_CUSTOM_NFG_LIAP),
AccelEvent("NF SimpDiv",SOLVE_CUSTOM_NFG_SIMPDIV),
AccelEvent("NF PolEnum",SOLVE_CUSTOM_NFG_POLENUM),
AccelEvent("NF Qre",SOLVE_CUSTOM_NFG_QRE),
AccelEvent("NF QreGrid",SOLVE_CUSTOM_NFG_QREGRID),
AccelEvent("Solve NormalForm",SOLVE_NFG),
AccelEvent("Reduced NF",SOLVE_NFG_REDUCED),
AccelEvent("Agent NF",SOLVE_NFG_AGENT),
AccelEvent("InspectSolutions",INSPECT_SOLUTIONS),
AccelEvent("InspectCursor",INSPECT_CURSOR),
AccelEvent("InspectInfosets",INSPECT_INFOSETS),
AccelEvent("InspectZoomWindow",INSPECT_ZOOM_WIN),
AccelEvent("InspectGameInfo",INSPECT_GAMEINFO),
AccelEvent("PrefsZoom",DISPLAY_SET_ZOOM),
AccelEvent("PrefsDisplay",DISPLAY_SET_OPTIONS),
AccelEvent("PrefsLegend",DISPLAY_LEGENDS),
AccelEvent("PrefsColors",DISPLAY_COLORS),
AccelEvent("PrefsAccels",DISPLAY_ACCELS),
AccelEvent("PrefsSaveDefault",DISPLAY_SAVE_DEFAULT),
AccelEvent("PrefsLoadDefault",DISPLAY_LOAD_DEFAULT),
AccelEvent("PrefsSaveCustom",DISPLAY_SAVE_CUSTOM),
AccelEvent("PrefsLoadCustom",DISPLAY_LOAD_CUSTOM),
AccelEvent("Help",GAMBIT_HELP_CONTENTS),
AccelEvent("HelpAbout",GAMBIT_HELP_ABOUT),
AccelEvent("ZoomIn",DISPLAY_INC_ZOOM),
AccelEvent("ZoomOut",DISPLAY_DEC_ZOOM),
AccelEvent("Redraw",DISPLAY_REDRAW),
};

#endif
