// Constants for display legends.  See legend.h
#define	LEGEND_END							-1
#define NODE_ABOVE_NOTHING			0
#define NODE_ABOVE_LABEL				1
#define	NODE_ABOVE_PLAYER				2
#define	NODE_ABOVE_ISETLABEL		3
#define	NODE_ABOVE_ISETID				4
#define NODE_ABOVE_OUTCOME			5
#define NODE_ABOVE_REALIZPROB		6
#define NODE_ABOVE_BELIEFPROB		7
#define NODE_ABOVE_VALUE				8

#define NODE_BELOW_NOTHING			0
#define NODE_BELOW_LABEL				1
#define	NODE_BELOW_PLAYER				2
#define	NODE_BELOW_ISETLABEL		3
#define	NODE_BELOW_ISETID				4
#define NODE_BELOW_OUTCOME			5
#define NODE_BELOW_REALIZPROB		6
#define NODE_BELOW_BELIEFPROB		7
#define NODE_BELOW_VALUE				8


#define BRANCH_ABOVE_NOTHING		0
#define BRANCH_ABOVE_LABEL			1
#define	BRANCH_ABOVE_PLAYER			2
#define BRANCH_ABOVE_PROBS			3
#define BRANCH_ABOVE_VALUE			4

#define BRANCH_BELOW_NOTHING		0
#define BRANCH_BELOW_LABEL			1
#define	BRANCH_BELOW_PLAYER			2
#define BRANCH_BELOW_PROBS			3
#define BRANCH_BELOW_VALUE			4

#define	NODE_TERMINAL_NOTHING		0
#define	NODE_TERMINAL_OUTCOME		1
#define	NODE_TERMINAL_NAME			2

#define NODE_RIGHT_NOTHING			0
#define NODE_RIGHT_OUTCOME			1
#define NODE_RIGHT_NAME					2

