name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: software-component
    attributes:
      label: Where did you find this bug?
      multiple: true
      options:
        - PyGambit
        - Gambit CLI
        - Gambit GUI
        - Other
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see and provide a screenshot if appropriate.
      value: "A bug happened!"
    validations:
      required: true