name: Documentation Improvement
description: Suggest a change to the Gambit documentation.
title: "[Documentation]: "
labels: ["documentation"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this documentation improvement request!
  - type: textarea
    id: request-details
    attributes:
      label: Requested documentation improvement
      description: Please provide details about the documentation improvement you would like to see. If you want to edit a specific page, please include the URL. If you have an idea for a new page, please explain where it should fit in the documentation structure.
      placeholder: Describe the documentation improvement in detail.
      value: "A documentation improvement suggestion!"
    validations:
      required: true