name: Tutorial request
description: Submit a request for a new tutorial to be added to the Gambit documentation.
title: "[Tutorial]: "
labels: ["tutorial", "documentation"]
body:
  - type: textarea
    id: describe
    attributes:
      label: Describe the tutorial you want to see.
      description: Go into as much detail as you can regarding the tutorial you would like to see, how long it should be etc.
      value: "Add a tutorial demonstrating the core components of the PyGambit API."
    validations:
      required: true
  - type: textarea
    id: describe
    attributes:
      label: Who is the tutorial for?
      description: Explain who the target audience is for this tutorial and what prior knowledge they should have.
      value: "Newcomers to game theory and the Gambit software who have basic Python programming skills."
    validations:
      required: true
  - type: textarea
    id: links
    attributes:
      label: Add links to papers and software.
      description: Add links to any research papers or other resources the author will need to write this tutorial.
      value: ""
