#! /bin/sh

echo
echo ------------------------------------------------------------
echo Gambit GUI installation script.
echo ------------------------------------------------------------

echo
echo The current binaries are:
echo gambit: `ls bin/gambit_*`
echo gcl:    `ls bin/gcl_*`
echo pxi:    `ls bin/pxi_*`
echo
echo Making symbolic links for gambit, gcl, and pxi.
cd bin
ln -s `echo gambit_*` gambit
ln -s `echo gcl_*` gcl
ln -s `echo pxi_*` pxi
cd ..

cd misc
gui-init
cd ..

echo
echo Installation script completed. 
echo
echo The gambit binaries are now in `pwd`/bin.
echo Please add this to your PATH environment variable 
echo in your .cshrc file 
echo
echo WARNING: do not change this directory without re-running
echo this installation script!


#
# Set up the appropriate environment variables.
# E.g. WXHELPFILES specifies where the help files reside.
#
