#! /bin/csh

echo This program will check and possibly update your Gambit GUI configuration
echo file: ~/.gambit.ini
if (-f ~/.gambit.ini) then
	echo Previous Gambit GUI init file found.
else 
	echo Creating a new Gambit GUI init file
	cp ./gambit.ini ~/.gambit.ini
endif

grep -s "Root-Dir" ~/.gambit.ini
if ($status) then
	set gambit-install-dir `pwd | sed -e 's/\/[^/]*//'`
	echo Setting the local install dir to : $gambit-install-dir
	echo "Install.Root-Dir:       " $gambit-install-dir >> ~/.gambit.ini
	echo Setting the local help dir to : $gambit-install-dir/doc
	echo "Install.Help-Dir:       " $gambit-install-dir/doc >> ~/.gambit.ini
else
	echo Local dir variables already set, no changes made
endif

