#! /bin/sh
#
# $Id$
#
# An update script/makefile combination to create/update GAMBIT components
# and automatically place them onto the primary GAMBIT ftp site.

# Usage: 
# update TARGET=[gambit, src, guidoc, gcldoc, all] 
#        SYSNAME=[Linux, SunOS_5_6, HPUX, all] 
#        GUI=[motif,xt,all]
#
# update calls 'make -f make.update'
#
# This can be started on any of the hss machines and it will update the files
# on the appropriate platform using rsh.  Since the GUI argument is not 
# used for any target except gambit, it may be left out in other cases.  However,
# to save a LOT of disk space and some time by avoiding recompiling all the
# non-gui common files, it is better to set GUI=motif if it is not used. 

# Note that specifying 'all' for any of the parameters will attempt to build
# targets with the parameter set to each of its possible values succesively.
# This may produce some duplicate combinations if more than one of the 
# parameters is set to all.  Duplicate builds take very little time and are
# not a problem.  Thus, to rebuild ALL of the components the command would be:
# update SYSNAME=all TARGET=all GUI=all 

make -f make.update $*


